apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-client-deployment
  labels:
    app: todo-app-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app-client
  template:
    metadata:
      labels:
        app: todo-app-client
    spec:
      containers:
      - name: todo-app-client
        image: todo-app-client:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app-client-service
spec:
  selector:
    app: todo-app-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP