apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-server-deployment
spec:
    replicas: 3
    selector:
      matchLabels:
        app: todo-app-server
    template:
      metadata:
        labels:
          app: todo-app-server
      spec:
        containers:
        - name: todo-app-server
          image: todo-app-server:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 5000
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: "localhost"
---

apiVersion: v1
kind: Service
metadata:
  name: todo-app-server-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
  selector:
    app: todo-app-server


#apiVersion: v1
#kind: Service
#metadata:
#  name: todo-app-server-service
#spec:
#  type: NodePort
#  ports:
#  - port: 5000
#    targetPort: 5000
#    protocol: TCP
#    nodePort: 30100
#  selector:
#    app: todo-app-server