apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-depl
  labels:
    app: reactapp

spec:
  template:
    metadata:
      name: my-frontend-pod
      labels:
        app: reactapp
    spec:
      containers:
        - name: my-frontend-container
          image: 6745345/my-react-image:release0

  replicas: 2
  selector:
    matchLabels:
      app: reactapp