apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: api-deployment
spec:
    replicas: 2
    selector:
      matchLabels:
        app: api-container
    template:
      metadata:
        namespace: production
        labels:
          app: api-container
      spec:
        containers:
        - name: api-container
          image: 6745345/api-image:Prod1.0
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 5000
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-url
              
---

apiVersion: v1
kind: Service
metadata:
 namespace: production
 name: api-service
spec:
 type: ClusterIP
 ports:
 - port: 5000
   targetPort: 5000
   protocol: TCP
 selector:
   app: api-container