version: '3.1'

services:
  postgresDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
       - C:\Users\mmale\Repozytoria\chmurowe\postgres\lab5\data:/var/lib/postgresql/data