version: '3'

services:
  api:
    # opis jak mamy stworzyć obraz do serwisu
    build:
      # sciezka do dockerfile danego serwisu
      dockerfile: Dockerfile
      # gdzie odbywa sie budowania
      context: ./backend
    # ustawianie zmiennych środowiskowych
    environment:
      - APIPORT=5001
    # mapowanie portow
    # host : container
    ports:
      - 5001:5001