version: '3'

services:
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports:
    - '3001:80'
    depends_on:
      - myfrontend

  myfrontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./myfrontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # kontener ma miec/widziec katalogi z hosta
      - /app/node_modules
       # powiedzenie ze kontener ma miec swoj node_modules
      - ./myfrontend:/app

      # 
      # C:\Users\mmale\Repozytoria\chmurowe\lab7\zadanie2\myfrontend:/app

      
     