version: '3'

services:
  mybackend:
    # jak cos sie zepsuje to sie restartuje
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./mybackend
    environment:
      - BACKENDPORT=4000
    volumes:
      - /app/node_modules
      - ./mybackend:/app
    
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports:
    - '3001:80'

  myfrontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./myfrontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      
    volumes:
      - /app/node_modules
      - ./myfrontend:/app